### ISSUE TITLE
Exception executing example - MNU SemanticConfig>>embeddingSize 

### ISSUE THREAD

**Issue by improvekit** [LinqLover/squeak-chatgpt#2]
![Screen Shot 2024-02-20 at 15 21 24](https://github.com/LinqLover/Squeak-SemanticText/assets/82164018/654b07f1-13f1-4b61-9ff6-016769acb6bb)

![Screen Shot 2024-02-20 at 15 23 05](https://github.com/LinqLover/Squeak-SemanticText/assets/82164018/3d4ef51f-e205-45e0-a200-bd8047908d84)

"Set up and populate semantic corpus"
helpTopics := CustomHelp asHelpTopic semanticDeepSubtopicsSkip: [:topic |
	topic title = 'All message categories']. "not relevant"
corpus := SemanticPluggableCorpus titleBlock: #title contentBlock: #contents.
corpus addFragmentDocumentsFromAll: helpTopics.
corpus estimatePriceToInitializeEmbeddings. 
corpus updateEmbeddings.

"Similarity search"
originTopic := helpTopics detect: [:ea | ea key = #firstContribution].
results := corpus findObjects: 10 similarToObject: originTopic.

"Semantic search"
results := corpus findObjects: 10 similarToQuery: 'internet connection'.
"Optionally, display results in a HelpBrowser"
resultsTopic := HelpTopic named: 'Search results'.
results do: [:ea | resultsTopic addSubtopic: ea].
resultsTopic browse.

**Comment by improvekit** [comment]
I downloaded last version I get this error, no problem with previous version

**Comment by LinqLover** [comment]
Thank you for the bug report @improvekit! Glad to see that anyone else is using this! :-)

Oops, looks like I forgot a migration when updating this recently. Can you please run this in a workspace and then try again?

```smalltalk
SemanticCorpus allSubInstancesDo: [:corpus |
	(corpus embeddingConfig isKindOf: SemanticEmbeddingConfig) ifFalse:
		[corpus embeddingConfig: (corpus embeddingConfig as: SemanticEmbeddingConfig)]].
```

**Comment by improvekit** [comment]
I run this chunk, but the same error raised

**Comment by LinqLover** [comment]
Sorry for that! Could you also try this instead?

```smalltalk
OpenAIEmbeddingModel allSubInstancesDo: [:model |
	(model baseConfig isKindOf: SemanticEmbeddingConfig) ifFalse:
		[model baseConfig: (model baseConfig as: SemanticEmbeddingConfig)]].
```

If this still does not help, maybe you can share a full bug report of the debugger (from the context menu of the debugger stack)?

**Comment by improvekit** [comment]
thank you, this solved the issue

**Comment by LinqLover** [comment]
Glad to hear that! Should not happen again.

(By the way, is there any chance to learn more about what is Dali, how it uses SemanticText, and whether SemanticText could do anything to support its use cases better? :-))
