### ISSUE TITLE
Syntax error during loading project into Squeak 6

### ISSUE THREAD

**Issue by improvekit** [LinqLover/squeak-chatgpt#4]
when doing from Squeak 6.0  (Apple Silicon)

![Screenshot 2024-05-18 at 5 15 08 PM](https://github.com/LinqLover/Squeak-SemanticText/assets/82164018/147b8bad-6f01-4536-8f2d-b0e0bb88c4c6)

Metacello new
	baseline: 'SemanticText';
	repository: 'github://LinqLover/Squeak-SemanticText:main';
	get; "for updates"
	load.

Loading is aborted and a window appears showing:

Syntax Error
calc: aString
	"Calculate a math expression."
	<function: "function signature expected ->"calc(expression: string "e.g., ""(2+3)*4"" or ""sqrt(5^2)-1""")>

**Comment by LinqLover** [comment]
Oh no! Will take a look at it this week. As a workaround, you can remove the entire line (`<function: ...>`) from the syntax error window and accept (Cmd + S) it.


________________________________
From: improvekit ***@***.***>
Sent: Saturday, May 18, 2024 10:16:29 PM
To: LinqLover/Squeak-SemanticText ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LinqLover/Squeak-SemanticText] Syntax error during loading project into Squeak 6 (Issue #4)


when doing from Squeak 6.0 (Apple Silicon)

Screenshot.2024-05-18.at.5.15.08.PM.png (view on web)<https://github.com/LinqLover/Squeak-SemanticText/assets/82164018/147b8bad-6f01-4536-8f2d-b0e0bb88c4c6>

Metacello new
baseline: 'SemanticText';
repository: 'github://LinqLover/Squeak-SemanticText:main';
get; "for updates"
load.

Loading is aborted and a window appears showing:

Syntax Error
calc: aString
"Calculate a math expression."
<function: "function signature expected ->"calc(expression: string "e.g., ""(2+3)*4"" or ""sqrt(5^2)-1""")>

**Comment by LinqLover** [comment]
@improvekit Should be fixed now (19d0184168b0e371c98bbf3292cdfcd9af062ed1), please report if you have any other issues!
